const cities = [
    "Tehran",
    "Mashhad",
    "Isfahan	",
    "Karaj",
    "Shiraz",
    "Tabriz",
    "Qom",
    "Ahvaz",
    "Kermanshah",
    "Urmia",
    "Rasht",
    "Zahedan",
    "Hamadan",
    "Kerman",
    "Yazd",
    "Ardabil",
    "Bandar Abbas",
    "Arak",
    "Eslamshahr",
    "Qazvin",
    "Zanjan",
    "Khorramabad",
    "Sanandaj",
    "Malard",
    "Qods",
    "Kashan",
    "Gorgan",
    "Golestan",
    "Sari",
    "Shahriar",
    "Dezful",
    "Khomeyni",
    "Borujerd",
    "Nishapur",
    "Sabzevar",
    "Najafabad",
    "Amol",
    "Babol",
    "Varamin",
    "Abadan",
    "Pakdasht",
    "Khoy",
    "Saveh",
    "Bojnord",
    "Qaem Shahr",
    "Bushehr",
    "Qarchak",
    "Sirjan",
    "Birjand",
    "Ilam",
    "Bukan",
    "Maragheh",
    "Malayer Hamadan	",
    "Shahr-e Kord	",
    "Bandar-e Mahshahr",
    "Semnan",
    "Rafsanjan",
    "Mahabad",
    "Gonbad-e Kavus",
    "Shahin Shahr",
    "Shahrud",
    "Saqqez",
    "Marvdasht",
    "Zabol",
    "Torbat-e Heydarieh",
    "Khorramshahr",
    "Andimeshk",
    "Marand",
    "Shahreza",
    "Miandoab",
    "Izeh",
    "Bandar-e Anzali",
    "Jahrom	",
    "Jiroft",
    "Kamal Shahr",
    "Yasuj",
    "Nazarabad",
    "Behbahan",
    "Bam",
    "Fasa",
    "Quchan",
    "Masjed Soleyman",
    "Mohammadshahr",
    "Dorud",
    "Borazjan",
    "Fardis",
    "Nasimshahr",
    "Andisheh",
    "Iranshahr",
    "Baneh",
    "Chabahar",
    "Robat Karim",
    "Kashmar",
    "Shushtar",
    "Lahijan",
    "Ahar",
    "Torbat-e Jam",
]

function linearSearch(arr, val){
    for(var i = 0; i < arr.length; i++){
        if(arr[i].toLowerCase() === val || arr[i] === val){
            return `${val} is the city number ${i+1}`
        }
    }
    return `${val} is not located in Iran`;
}

console.log(linearSearch(cities,"mashhad"))
